### ISSUE TITLE
How to understand "statically unpredictable data accesses or control flow"?

### ISSUE THREAD

**Issue by QiJune** [tensorflow/mlir#19]
I am confused with this sentence. 
> The presence of statically unpredictable data accesses or control flow does not preclude representation in MLIR, but only limits to a certain extent the ability to reason about and apply transformations using the polyhedral abstraction

Locates in [Rationale](https://github.com/tensorflow/mlir/blob/master/g3doc/Rationale.md#introduction-and-motivation) doc.

Does the unpredictable means that the value of some symbols are determined at runtime, so which branch to go is unpredictable?

Could you please give some detail examples? Thanks!

**Comment by albertcohen** [comment]
Hi,
Unpredictable means data-dependent indexing or (loop/conditional) control flow. E.g. subscripting a memref with the return value of a function, or a value from another memref, will break the precise analyses of memref dependences, footprints, etc. Or a loop bound defined inductively from other values rather than a static affine expression (an attribute). The affine dialect typically enforces stronger restrictions on data access and control flow, but there are no such restrictions in general MLIR.
Thanks for your remark, I plan to improve the rationale doc to clarify accordingly.
Albert

**Comment by QiJune** [comment]
Thanks for the interpretation, It helps a lot!
