### ISSUE TITLE
Bugs in examples/Linalg2 TensorOps.h ?

### ISSUE THREAD

**Issue by yehenrytian** [tensorflow/mlir#26]
In the Linalg dialect example: `examples/Linalg/Linalg2/include/linalg2/TensorOps.h` why the 3 op classes are all defined with `mlir::OpTrait::ZeroResult`?

```c++
/// Implements c = A * B where c is a scalar and A and B are 1-D vectors.
class DotOp : public TensorContractionBase<DotOp>,
              public mlir::Op<DotOp, mlir::OpTrait::VariadicOperands,
                              mlir::OpTrait::ZeroResult> {


/// Implements C = A * B where A is a 2-D matrix and X and Y are 1-D vectors.
class MatvecOp : public TensorContractionBase<MatvecOp>,
                 public mlir::Op<MatvecOp, mlir::OpTrait::VariadicOperands,
                                 mlir::OpTrait::ZeroResult> {


/// Implements C = A * B on 2-D matrices.
class MatmulOp : public TensorContractionBase<MatmulOp>,
                 public mlir::Op<MatmulOp, mlir::OpTrait::VariadicOperands,
                                 mlir::OpTrait::ZeroResult> {
```

Why not `mlir::OpTrait::OneResult`? Thanks!

**Comment by joker-eph** [comment]
If you look for example here: https://github.com/tensorflow/mlir/blob/master/examples/Linalg/Linalg2/Example.cpp#L56 ; you'll see that these operations work by taking 3 views as operands: the two inputs and the result. A C++ equivalent would be:

```
void matmul(View Result, View LHS, View RHS);
```

Instead of:

```
View matmul(View LHS, View RHS);
```

Also the MLIR mailing-list is likely a good place for this kind of questions: https://groups.google.com/a/tensorflow.org/forum/#!forum/mlir
