### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [tensorflow/mlir#5]
Would you like to [add more error handling](https://github.com/tensorflow/mlir/blob/5ca84e0e2aa07f88164d196f12383757f9441ecc/lib/IR/Operation.cpp#L113 "Update candidate: Operation::create()") for return values from [functions like “malloc”](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation")?

**Comment by lattner** [comment]
We assume that operator new and malloc are always successful, and don't thread error handling through the compiler to handle it.  This is the same policy as LLVM.

**Comment by elfring** [comment]
* I find such an assumption [questionable](https://cwe.mitre.org/data/definitions/252.html "Checking more return values").
* How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by joker-eph** [comment]
> * I find such an assumption [questionable](https://cwe.mitre.org/data/definitions/252.html).

In general we are very much convinced by the link you provide about "Unchecked Return Value".
This is why we are currently moving our APIs that can fail to return our own class "LogicalResult" that we will mark a `no_discard` so that the compiler will warn when the returned value is unused.

However in the case of malloc, most platform (at least the ones running compilers) have an implementation that is allocating virtual memory independently of the physical memory available. That means that even when you don't have memory you won't get a null pointer as a result of malloc, but the physical pages are only allocated on the first access to the memory.
This is one reason why checking the return of malloc isn't helpful: you will get a valid pointer but the program may fault on a future memory access to the allocated region (which is hard/impossible to recover from).

Another aspect is that even if you get a null pointer (by configuring your kernel/allocator to prefault all the pages for instance), what do you do? Recovering from running out of memory is quite difficult in general: most applications (at least the kind that runs a compiler) would just exit in such case.

> * How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B) also for this software?

I am not sure I understand the question exactly, do you mind elaborating a little what you have in mind?

**Comment by elfring** [comment]
I suggest to [adhere to the known standard programming interfaces](https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors "Detect and handle standard library errors.") even if a result like [a null pointer](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers#EXP34-C.Donotdereferencenullpointers-RiskAssessment "Do not dereference null pointers.") can look unlikely.
* How do you think about to choose a more appropriate program error code finally?
* Are there other function calls (which can be shown by corresponding software development tools) also questionable?

**Comment by lattner** [comment]
@elfring this is a standard followed by the LLVM community, and we follow it.  If you would like to discuss this, I recommend you bring this to the public llvm-dev mailing list.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers#EXP34-C.Donotdereferencenullpointers-RiskAssessment "Do not dereference null pointers.")?

**Comment by joker-eph** [comment]
> How do you think about to avoid that this software depends on undefined behaviour?

We are running our test-suite with UBSAN (undefined behavior sanitizer), and we are aiming at being free of undefined behavior in general.

As Chris mentioned, I invite you to raise your concern to LLVM, but I suggest that you try there to include an answer to address in detail what I explained before about recovering from memory allocation failure.

Thanks!
